#ifndef CUSTOMSKILLSMODIFIERTYPE_H_
#define CUSTOMSKILLSMODIFIERTYPE_H_

class CustomSkillsModifierType {
public:
	enum Type {
		CRITICAL_CHANCE,
		DOUBLE_ATTACK_CHANCE,
		TRIPLE_ATTACK_CHANCE,
		QUAD_ATTACK_CHANCE,
		ARMOR_PENETRATION,
		DEFENSE_CAP_INCREASE,
		ARMOR_DEGRADE_REDUCTION,
		WEAPON_DEGRADE_REDUCTION,
		SEA_CAP_INCREASE,
		MOVEMENT_SPEED,
		BUFF_DURATION,
		EXPERIENCE_MULTIPLIER,
		PRACTICE_EXPERIENCE_BONUS,
		CRAFTING_SPEED,
		AMAZING_SUCCESS_CHANCE,
		AMAZING_RESULTS,
		GATHERING_QUANTITY,
		COUNT
	};
};

#endif
